apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#` is reserved for internal use and cannot be used in volumehandle
    volumeHandle: airflow-logs-unique-volumeid
    volumeAttributes:
      containerName: airflowlogs
    nodeStageSecretRef:
      name: azurecontinerstorage
      namespace: airflow