apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
spec:
  storageClassName: azureblob-fuse-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi    